packages:
  - "packages/*"
  - "apps/*"
allowBuilds:
  '@firebase/util': true
  '@parcel/watcher': true
  '@prisma/engines': true
  contextify: false
  cpu-features: true
  esbuild: true
  prisma: true
  protobufjs: true
  ssh2: true
  unrs-resolver: true
